AWSTemplateFormatVersion: "2010-09-09"
Description: cfn template to deploy SecretManager secret

Parameters:
  project:
    Type: String
    Description: Project Name
  env:
    Type: String
    Default: dev
    AllowedValues: [dev, qa, uat, prod]
    Description: Environment name
  app:
    Type: String
    Description: App Name
  # smName:
  #   Type: String
  #   Description: Name of secret 
  # smSecretString:
  #   Type: String
  #   Description: Text to store in the secret 

  smRdsUsername:
    Type: String
    NoEcho: true
    Description: Rds DB username to be stored as secret
  smRdsPassword:
    Type: String
    NoEcho: true
    Description: Rds DB password to be stored as secret
  smRdsDbName: 
    Type: String
    Description: Name of the Rds DB password to be stored as secret
  smRdsEndpoint: 
    Type: String
    Description: Rds endpoint to be stored as secret
  

Resources:
  rdsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: flask-app-secret

      SecretString: !Sub '{"username":"${smRdsUsername}","password":"${smRdsPassword}","db_name":"${smRdsDbName}","endpoint":"${smRdsEndpoint}"}'

      # Tags:
      # - Key: name
      #   Value: !Sub "${project}-${app}-${env}-{rdsSecret}-${AWS::Region}"
      # - Key: project
      #   Value: !Ref project
      # - Key: app
      #   Value: !Ref app
      # - Key: environment
      #   Value: !Ref env

Outputs:
  secretmanagerArn:
    Value: !Ref rdsSecret
    Export:
      Name: !Sub "${project}-${env}-secretmanagerArn-${AWS::Region}"