AWSTemplateFormatVersion: "2010-09-09"
Description: main yml file for security groups

Parameters:
  project:
    Type: String
    Description:  Project Name
    Default: devops-training
  app:
    Type: String
    Description:  Application Name
    Default: app
  env:
    Type: String
    Description:  Environment Name
    Default: dev

  smRdsUsername:
    Type: String
    NoEcho: true
    Description: Rds DB username to be stored as secret
  smRdsPassword:
    Type: String
    NoEcho: true
    Description: Rds DB password to be stored as secret
  smRdsDbName: 
    Type: String
    Description: Name of the Rds DB password to be stored as secret
  # smRdsEndpoint: 
  #   Type: String
  #   Description: Rds endpoint to be stored as secret


  s3ArtifactPath:
    Type: String
    Description: Artifact Bucket Path
    # Default: "https://devops-crosstrack-training.s3.amazonaws.com/code/experienced-resource-training/saad/cfn/services/"
    Default: "https://sad-app-bucket.s3.amazonaws.com/flask-app-deploymment-using-cfn/cfn/services/"


Resources:
  smSecret:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${s3ArtifactPath}secretsmanager/secretsmanager-app.yml"
      Parameters:
        project: !Ref project
        app: !Ref app
        env: !Ref env
        smRdsUsername: !Ref smRdsUsername
        smRdsPassword: !Ref smRdsPassword
        smRdsDbName: !Ref smRdsDbName
        smRdsEndpoint: !ImportValue 
          Fn::Sub: "${project}-${env}-rdsEndpoint-${AWS::Region}"
          # Fn::Sub: "${project}-${app}-${env}-rdsEndpoint-${AWS::Region}"




Outputs:
  smStackId:
    Description: Secret Manager stack ID
    Value: !Ref smSecret
    Export:
      Name: !Sub "${project}-${app}-${env}-smStackId-${AWS::Region}"


